name: Build TimeZoneApp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # GitHub-hosted Windows runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet publish -c Release -o ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: TimeZoneApp
        path: ./publish  # Upload the build output as an artifact
